name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-gcc:
    name: Build with GCC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y gcc g++ cmake ninja-build
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
      - name: Build and Test
        run: |
          cmake --build build --config Release
          ctest --test-dir build --output-on-failure

  build-clang:
    name: Build with Clang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Clang
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      - name: Build and Test
        run: |
          cmake --build build --config Release
          ctest --test-dir build --output-on-failure

  build-apple-clang:
    name: Build with Apple Clang
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      - name: Build and Test
        run: |
          cmake --build build --config Release
          ctest --test-dir build --output-on-failure

  build-msvc:
    name: Build with MSVC
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build and Test
        run: |
          cmake --build build --config Release
          ctest --test-dir build --output-on-failure
